// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzTCH_VAw4s-UGeGtUdHji5hQSz2-zvU',
    appId: '1:601168868277:web:b020455a8ce4ac7a001ffc',
    messagingSenderId: '601168868277',
    projectId: 'smartcheckpoint-e87cd',
    authDomain: 'smartcheckpoint-e87cd.firebaseapp.com',
    storageBucket: 'smartcheckpoint-e87cd.firebasestorage.app',
    measurementId: 'G-PWN1CGJHE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-3tmj38VHZ78Jd6J01UA3XamXdhOq08',
    appId: '1:601168868277:android:61a2d8111a00f44d001ffc',
    messagingSenderId: '601168868277',
    projectId: 'smartcheckpoint-e87cd',
    storageBucket: 'smartcheckpoint-e87cd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAVoA30h5ndBmyTdy5tKk8L5ELDZK7TI',
    appId: '1:601168868277:ios:10525a58362984b6001ffc',
    messagingSenderId: '601168868277',
    projectId: 'smartcheckpoint-e87cd',
    storageBucket: 'smartcheckpoint-e87cd.firebasestorage.app',
    iosClientId: '601168868277-brqr15qr99jku47h8k0e44ohccn1booh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQAVoA30h5ndBmyTdy5tKk8L5ELDZK7TI',
    appId: '1:601168868277:ios:10525a58362984b6001ffc',
    messagingSenderId: '601168868277',
    projectId: 'smartcheckpoint-e87cd',
    storageBucket: 'smartcheckpoint-e87cd.firebasestorage.app',
    iosClientId: '601168868277-brqr15qr99jku47h8k0e44ohccn1booh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxzTCH_VAw4s-UGeGtUdHji5hQSz2-zvU',
    appId: '1:601168868277:web:73f26cb78cd3c0b5001ffc',
    messagingSenderId: '601168868277',
    projectId: 'smartcheckpoint-e87cd',
    authDomain: 'smartcheckpoint-e87cd.firebaseapp.com',
    storageBucket: 'smartcheckpoint-e87cd.firebasestorage.app',
    measurementId: 'G-2LQNYSZWJL',
  );
}
